# Generated by Django 4.2.3 on 2023-07-27 00:33

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('generic', '0003_genericpagebannerimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericpagebannerimage',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banner_image', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='genericpagebannerimage',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='banner_image', to='generic.genericpage'),
        ),
    ]
